// ─── MOCK DATA ────────────────────────────────────────────────────────────────
// Used as fallback when the backend is unreachable (demo / GitHub Pages deploy).
// Schema matches the real MongoDB documents the API returns.

export const MOCK_INCIDENTS = [
  {
    _id: 'mock-001',
    incidentType: 'Wildfire Outbreak',
    location: 'Nainital Forest Reserve, Uttarakhand',
    urgency: 'CRITICAL',
    status: 'Active',
    peopleAffected: 3400,
    resourcesNeeded: ['Fire Brigades', 'Helicopters', 'Medical Teams', 'Water Tankers'],
    verificationStatus: 'Verified',
    description: 'Rapidly spreading wildfire engulfing 2,000+ acres of dense forest. Evacuation of nearby villages underway.',
    coordinates: { lat: 29.3803, lng: 79.4636 },
    reportedBy: 'Forest Dept. Control Room',
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
  },
  {
    _id: 'mock-002',
    incidentType: 'Flash Flood',
    location: 'Brahmaputra Riverside, Assam',
    urgency: 'HIGH',
    status: 'Escalated',
    peopleAffected: 8700,
    resourcesNeeded: ['Rescue Boats', 'NDRF Teams', 'Food Supplies', 'Temporary Shelters'],
    verificationStatus: 'Verified',
    description: 'Sudden flash flooding following dam overflow. Over 200 villages cut off. Road connectivity disrupted.',
    coordinates: { lat: 26.1445, lng: 91.7362 },
    reportedBy: 'District Collector Office',
    createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    _id: 'mock-003',
    incidentType: 'Building Collapse',
    location: 'Dharavi, Mumbai, Maharashtra',
    urgency: 'CRITICAL',
    status: 'Rescue in Progress',
    peopleAffected: 560,
    resourcesNeeded: ['Search & Rescue', 'Cranes', 'Ambulances', 'Trauma Surgeons'],
    verificationStatus: 'Verified',
    description: '6-storey residential building collapsed due to structural failure. Trapped victims reported on multiple floors.',
    coordinates: { lat: 19.0388, lng: 72.8520 },
    reportedBy: 'BMC Emergency Cell',
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
  {
    _id: 'mock-004',
    incidentType: 'Earthquake Aftershock',
    location: 'Manipur-Myanmar Border Zone',
    urgency: 'HIGH',
    status: 'Active',
    peopleAffected: 12000,
    resourcesNeeded: ['Army Deployment', 'Medical Supplies', 'Satellite Phones', 'Generators'],
    verificationStatus: 'Verified',
    description: 'M6.1 earthquake with multiple aftershocks. Power lines down, hospitals overwhelmed. International aid requested.',
    coordinates: { lat: 24.4637, lng: 94.0060 },
    reportedBy: 'National Disaster Management Authority',
    createdAt: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
  },
  {
    _id: 'mock-005',
    incidentType: 'Gas Pipeline Explosion',
    location: 'HPCL Refinery, Visakhapatnam, AP',
    urgency: 'HIGH',
    status: 'Active',
    peopleAffected: 240,
    resourcesNeeded: ['Fire Brigades', 'Hazmat Teams', 'Evacuation Buses', 'Air Ambulances'],
    verificationStatus: 'Verified',
    description: 'Major gas leak followed by explosion at refinery unit. 3km exclusion zone established. Workers unaccounted for.',
    coordinates: { lat: 17.6868, lng: 83.2185 },
    reportedBy: 'HPCL Safety Officer',
    createdAt: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
  },
  {
    _id: 'mock-006',
    incidentType: 'Landslide',
    location: 'NH44 – Banihal Pass, Jammu',
    urgency: 'MEDIUM',
    status: 'Active',
    peopleAffected: 1100,
    resourcesNeeded: ['JCB Machines', 'Police Barricades', 'First Aid Units'],
    verificationStatus: 'Verified',
    description: 'Heavy rainfall triggered landslide blocking national highway. 30+ vehicles stranded. Alternate route unavailable.',
    coordinates: { lat: 33.5000, lng: 75.2000 },
    reportedBy: 'NHAI Patrol Unit',
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
  },
  {
    _id: 'mock-007',
    incidentType: 'Mass Stampede',
    location: 'Kumbh Mela Grounds, Prayagraj, UP',
    urgency: 'HIGH',
    status: 'Rescue in Progress',
    peopleAffected: 3800,
    resourcesNeeded: ['Police Reinforcements', 'Medical Teams', 'Crowd Control Barriers'],
    verificationStatus: 'Verified',
    description: 'Stampede during dawn aarti causing multiple casualties. Overcrowding at Sangam Ghat. Mass casualty protocol invoked.',
    coordinates: { lat: 25.4358, lng: 81.8463 },
    reportedBy: 'UP Police Control Room',
    createdAt: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
  },
  {
    _id: 'mock-008',
    incidentType: 'Cyclone Landfall',
    location: 'Puri Coastal Belt, Odisha',
    urgency: 'CRITICAL',
    status: 'Escalated',
    peopleAffected: 52000,
    resourcesNeeded: ['Coast Guard', 'Cyclone Shelters', 'ODRAF Deployment', 'Telecom Restoration'],
    verificationStatus: 'Verified',
    description: 'Category 4 cyclone making landfall. 160 km/h wind speeds. Pre-emptive evacuation of 500k people ongoing.',
    coordinates: { lat: 19.8135, lng: 85.8312 },
    reportedBy: 'IMD Cyclone Warning Centre',
    createdAt: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
  },
  {
    _id: 'mock-009',
    incidentType: 'Industrial Chemical Spill',
    location: 'GIDC Industrial Zone, Surat, Gujarat',
    urgency: 'MEDIUM',
    status: 'Active',
    peopleAffected: 420,
    resourcesNeeded: ['Hazmat Teams', 'Containment Equipment', 'Evacuation Support'],
    verificationStatus: 'Unverified',
    description: 'Chlorine gas leak from chemical storage tank. Workers being evacuated. Residents within 1km advised to stay indoors.',
    coordinates: { lat: 21.1702, lng: 72.8311 },
    reportedBy: 'Factory Safety Inspector',
    createdAt: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    _id: 'mock-010',
    incidentType: 'Drought & Water Crisis',
    location: 'Marathwada Region, Maharashtra',
    urgency: 'MEDIUM',
    status: 'Resolved',
    peopleAffected: 180000,
    resourcesNeeded: ['Water Tankers', 'Borewell Drilling', 'Relief Funds'],
    verificationStatus: 'Verified',
    description: 'Severe water scarcity across 11 districts. Tanker supply stabilised. State govt emergency relief disbursed.',
    coordinates: { lat: 19.4600, lng: 76.5700 },
    reportedBy: 'Maharashtra Water Authority',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
];
